# Generated by Django 4.1.1 on 2023-04-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='housename',
            new_name='houseno',
        ),
    ]
