# Generated by Django 4.1.1 on 2023-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_rename_housename_profile_houseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='med_description',
            field=models.TextField(null=True),
        ),
    ]
