# Generated by Django 4.1.1 on 2023-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_products_med_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='med_usage',
            field=models.TextField(null=True),
        ),
    ]
