# Generated by Django 4.1.1 on 2023-04-28 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='addedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
